GJ_AI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='main'),
    path('admin/', admin.site.urls),
    path('myself/', include('myself.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/',include('likeapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myself/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from myself.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'myself'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='myself/login.html'),
         name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), #숫자를 받을것. primary key
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/',ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(),name='update'),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True) #지워도 작성자미상의 글로 남도록.
    project = models.ForeignKey(Project,on_delete=models.SET_NULL,
                                related_name='article',null=True,blank=True)
    title = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to='article',null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True,null=True)

    like = models.IntegerField(default=0)

myself/models.py
from django.db import models

# Create your models here.
 #python manage.py makemigrations 하면 생성되는 0001_initial.py 파일은 변화를 추적해주므로 지우지 말것.
class NewModel(models.Model) : #장고에서 기본적으로 제공하는 모델
    text = models.CharField(max_length=255, null=False)

myself/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm) :
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) #상속받은 값을 그대로 사용

        self.fields['username'].disabled = True

myself/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from myself.decorators import account_ownership_required
from myself.forms import AccountCreationForm
from myself.models import NewModel

#view 간단히.

class AccountCreateView(CreateView) :
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list') #함수에서는 reverse, class 에서는 reverse_lazy
    template_name = 'myself/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin) :
    model = User
    context_object_name = 'target_user'
    template_name = 'myself/detail.html'
    paginate_by = 15

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list,**kwargs)
has_ownership = [login_required,account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')

class AccountUpdateView(UpdateView) : #수정할 객체를 찾고, 저장하는 과정
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'myself/update.html'

    def get_success_url(self):
        return reverse('myself:detail',kwargs={'pk':self.object.pk})

has_ownership = [login_required,account_ownership_required]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView) :
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('myself:login')
    template_name = 'myself/delete.html'

myself/templates/myself/create.html
{% extends 'index.html' %}]
{% load bootstrap4 %}

{% block content %}

    <div class = "text-center mw-500 m-auto">
        <div class = "m-5"> <!-- 상하좌우 모두 5만큼-->
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'myself:create' %}" method = "post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-4">
                    <input type="submit"
                           class="btn btn-info px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

myself/templates/myself/delete.html
{% extends 'index.html' %}]
<!-- form 필요없음 {% load bootstrap4 %} -->

{% block content %}


    <div class = "text-center mw-500 m-auto">
        <div class = "m-5"> <!-- 상하좌우 모두 5만큼-->
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'myself:delete' pk=target_user.pk %}" method = "post">
                {% csrf_token %}
                <div class = "m-4">
                    <input type="submit"
                           class="btn btn-danger px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}

myself/templates/myself/detail.html
{% extends 'index.html' %}]


{% block content %}


    <div class = "text-center mw-500 m-auto">
        <div class = "m-5"> <!-- 상하좌우 모두 5만큼-->
            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}"
                     class = "profile_image m-4" {# 상하좌우마진까지 #}
                     alt="profile image">
                <h2 class = "NNS_B">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                            class="material-icons round_button">
                            edit
                        </a>
                    {% endif %}
                </h2>
                <h5>{{ target_user.profile.message }}</h5>
            {% else %}
            <h4>
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>
            </h4>
            {% endif%}
        </div>

        {% if user == target_user %} {# 회원이 일치하지 않으면 뜨지 않게 #}

        <div class = 'm-2'>
            <a href="{% url 'myself:update' pk=target_user.pk %}"
            class ="material-icons round_button mx-1">
                settings
            </a>
        </div>
        <div>
            <a href="{% url 'myself:delete' pk=target_user.pk %}"
            class ='material-icons round_button mx-1'>
                close
            </a>
        </div>

        {% endif %}
    </div>
    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>

{% endblock %}

myself/templates/myself/login.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class = "text-center mw-300 m-auto">
        <div class = "m-5"> <!-- 상하좌우 모두 5만큼-->
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'myself:login' %}" method = "post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-4">
                    <input type="submit"
                           class="btn btn-info px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}

myself/templates/myself/update.html
{% extends 'index.html' %}]
{% load bootstrap4 %}

{% block content %}


    <div class = "text-center mw-500 m-auto">
        <div class = "m-5"> <!-- 상하좌우 모두 5만큼-->
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'myself:update' pk=target_user.pk %}" method = "post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-4">
                    <input type="submit"
                           class="btn btn-info px-5">
                </div>
            </form>
        </div>
    </div>



{% endblock %}