GJ_AI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='main'),
    path('admin/', admin.site.urls),
    path('myself/', include('myself.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscribe/', include('subscribeapp.urls')),
    path('likes/',include('likeapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(),name='delete')
]

myself/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from myself.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'myself'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='myself/login.html'),
         name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), #숫자를 받을것. primary key
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/',ProjectCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(),name='detail'),
    path('list/', ProjectListView.as_view(),name="list"),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name='subscribeapp'
urlpatterns = [
    path('subscribe/<int:project_pk>',SubscriptionView.as_view(),name='subscribe'),
    path('list/',SubscriptionListView.as_view(),name='list')
]

templates/footer.html
<div style = "text-align: center; margin-bottom : 2rem;">
    <div class = "JururuK_footer_button">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>고객센터</span>
    </div>
    <div class = "JururuK_footer_logo">
        <p> 2021.09.10</p>
        <h5>GIS</h5>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>Title</title>
    {#boot strap link#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    {# google font link #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jua&family=Nanum+Myeongjo:wght@700&display=swap" rel="stylesheet">
    {# default css link #}
    <link rel = "stylesheet" type = "text/css" href="{% static 'index.css' %}">
    {# naver font #}

    {# material icons link #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'), {# 있으면 로컬서버의 것, 없으면 아래 #}
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div style = "text-align : center">
    <div class="JururuK_header_logo">  <!-- rem 앞은 상하, 뒤는 좌우 나눔명조 적용이안되면 serif를 적용 -->
        <a href="{% url 'main' %}">
            <h1>JururuK's</h1>
        </a>

    </div>
    <div class="JururuK_header_button">
        <span class="mx-2">|
            <a href="{% url 'articleapp:list' %}">
                articles
            </a>
        </span>|
        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">
                projects
            </a>
        </span>|
        {% if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'myself:login' %}">
                Login
            </a>
        </span>|

        <span class="mx-2">
            <a href="{% url 'myself:create' %}">
                 Sign Up
            </a>
        </span>|
        {% else %}
        <span>
            <a href="{% url 'myself:detail' pk=user.pk %}">
                MyPage
            </a>
        </span>|
        <span class="mx-2">
            <a href="{% url 'subscribeapp:list' %}">
                Subscribes
            </a>
        </span>|
        <span>
            <a href="{% url 'myself:logout' %}">
                Logout
            </a>
        </span>
        {% endif %}
    </div>

</div>

templates/index.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body style = 'font-family: "NanumSquareR"'>

    {% include 'header.html' %}
<hr>

{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
            {{ message }}
        <div>
    </div>
{% endfor %}

{% block content %}

{% endblock %}
<hr>
    {% include 'footer.html' %}

</body>
</html>